require_recipe "apt"
package "vim"
package "curl"
package "wget"
package "rsync"
package "man-db"
package "strace"
package "host"
package "lsof"
package "gdb"
package "socat"
package "ack-grep"
package "sysstat"
package "byobu"
package "aptitude"

